--------- AS THE GUIDELINE FOR CONSTRUING THE DB ----------


-- FOR DATABASE STRUCTURE SETUP
CREATE DATABASE IF NOT EXISTS user_auth;

-- FOR USER AUTHENTICATION
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- FOR CT SCAN IMAGES
CREATE TABLE ct_scans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    image_data LONGBLOB NOT NULL,
    image_name VARCHAR(255) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
